Importa numpy

In [1]:
import numpy as np

crea un numpy array que tenga la siguente estructura

```
[[1,  6, 11],
 [2,  7, 12],
 [3,  8, 13],
 [4,  9, 14],
 [5, 10, 15]]
```

llamalo `array`

In [2]:
array = np.array([
    [1, 6, 11],
    [2, 7, 12],
    [3, 8, 13],
    [4, 9, 14],
    [5, 10, 15]
])

array

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

averigua la forma del array

In [4]:
array.ndim
array.shape

(5, 3)

Selecciona la segunda columna del array

In [8]:
array[:,1]

array([ 6,  7,  8,  9, 10])

 Crea un vector con los valores del 15 al 55, llamalo array2
    
*pista: usa np.arange*

In [11]:
array2 = np.arange(15,56,1)
array2

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
       49, 50, 51, 52, 53, 54, 55])

asigna el valor 23 a la quinta posicion del array2

In [12]:
array2[4] = 23
array2

array([15, 16, 17, 18, 23, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
       49, 50, 51, 52, 53, 54, 55])

convierte array2 del revés (es decir `[55,54,....,15]`

In [16]:
array2[::-1]

array([55, 54, 53, 52, 51, 50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39,
       38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22,
       21, 20, 23, 18, 17, 16, 15])

Crea una matriz diagonal donde los elementos de la diagonal sean los 5 primeros valores pares de array2, llamala `matriz_diag`

*pista: usa np.diag*

In [32]:
matriz_diag = np.diag(array2[1::2][:5])
matriz_diag

array([[16,  0,  0,  0,  0],
       [ 0, 18,  0,  0,  0],
       [ 0,  0, 20,  0,  0],
       [ 0,  0,  0, 22,  0],
       [ 0,  0,  0,  0, 24]])

Imprime el numero de dimensiones de `matriz_diag`

In [36]:
matriz_diag.ndim
matriz_diag.shape

(5, 5)

Crea una matriz con números aleatorios de tamaño 5x3 (4 filas por 3 columnas), llamala `matriz`

In [33]:
matriz = np.random.random((5,3))
matriz

array([[0.62546768, 0.52919757, 0.92562547],
       [0.1098083 , 0.76910815, 0.93970885],
       [0.69965903, 0.97119963, 0.90461719],
       [0.88563595, 0.13305242, 0.4492929 ],
       [0.71530918, 0.17865863, 0.948355  ]])

multiplica `matriz` por `matriz_diag`

In [34]:
matriz.T.shape

(3, 5)

In [37]:
matriz.T @ matriz_diag

array([[10.00748285,  1.97654933, 13.99318069, 19.4839908 , 17.16742029],
       [ 8.46716115, 13.84394666, 19.42399257,  2.92715327,  4.28780701],
       [14.8100075 , 16.91475927, 18.09234373,  9.88444372, 22.76052008]])